[versions]
kotlin = "2.3.0"
ktlint-plugin = "12.3.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version = "2.0.0-SNAPSHOT" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }